### ISSUE TITLE
Messages still clipped in Firefox

### ISSUE THREAD

**Issue by ojchase** [jeremejevs/trimless-gmail#36]
I think this is basically the Firefox version of issue #34.  I installed Trimless specifically to have clipped messages actually show in full without having to click "View entire message", and that's not happening in Firefox.  I've also installed it in Chrome, and the same two messages are fully "unclipped" in Chrome as expected, so it's specifically Firefox.  The scissors icon is red in both browsers.  Version is current, browser and gmail tab have been restarted a few times, etc.  Basic Gmail, not a custom domain.  I'm getting a decent amount of output in the console, so I'll wait for confirmation that it's necessary before sending.  (Would you prefer screenshots or text?)  This is Firefox Quantum 59.0 (64-bit)

**Comment by jeremejevs** [comment]
Can you, please, confirm, that you're using `1.10.2`? Through `about:addons`? The stats show me that a few people are still on `1.10.1`, which is the broken one. Maybe yours has failed to auto-update.

If you are on `1.10.2`, then yeah, gotta take a look at the console. I'm normally in favor of text, but in this case, I think screenshots are preferable, since the formatting doesn't get preserved when copying.

**Comment by ojchase** [comment]
Sorry, should have explicitly said `1.10.2`.  It is, as you'd hope from a fresh installation!  I'll send you console screenshots.
